import '@/styles/normalize.css'
import '@/styles/global.scss'
import '@/styles/css-variables.scss'
import '@/styles/quill.css'

import { Metadata, Viewport } from 'next'
import { Roboto } from 'next/font/google'

import { themeScript } from '@/utils/theme'

import { Layout } from './_components/Layout'

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // maximumScale: 1,
  viewportFit: 'cover',
  themeColor: '#5031aa'
}

const robotoFont = Roboto({
  variable: '--primary-font',
  weight: ['400', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  fallback: [
    '-apple-system',
    'BlinkMacSystemFont',
    'Segoe UI',
    'Roboto',
    'Oxygen',
    'Ubuntu',
    'Cantarell',
    'Fira Sans',
    'Droid Sans',
    'Helvetica Neue',
    'Arial',
    'sans-serif'
  ]
})

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
  robots: 'noindex'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <html className={robotoFont.variable} lang='en' suppressHydrationWarning>
        <head>
          <script
            dangerouslySetInnerHTML={{
              __html: themeScript
            }}
          />
        </head>
        <Layout>{children}</Layout>
      </html>
    </>
  )
}
